import type { CapacitorConfig } from '@capacitor/cli';
import { KeyboardResize } from '@capacitor/keyboard';
import appConfig from './app.config.json';

/**
 * Hosted-URL architecture: the native shell loads the web app from APP_URL in its WebView.
 * Capacitor is used only for native features (SQLite, haptics, status bar, keyboard …).
 * `shell/` is a tiny bundled fallback (offline / load-error page) generated by
 * scripts/build-shell.mjs.
 */
// APP_URL env (CI / local testing) overrides the committed Vercel URL in app.config.json.
const appUrl = process.env.APP_URL || appConfig.appUrl;
const appHost = new URL(appUrl).hostname;

const config: CapacitorConfig = {
  appId: 'com.webronian.gymtracker',
  appName: 'Gym Tracker',
  webDir: 'shell',
  server: {
    url: appUrl,
    cleartext: false,
    allowNavigation: [appHost],
    errorPath: 'offline.html',
  },
  ios: {
    contentInset: 'never',
    scrollEnabled: true,
    allowsLinkPreview: false,
    backgroundColor: '#f2f2f7',
    // Needed for the service worker (offline cache) in WKWebView; host listed in
    // Info.plist WKAppBoundDomains.
    limitsNavigationsToAppBoundDomains: true,
  },
  android: {
    allowMixedContent: false,
    captureInput: true,
    webContentsDebuggingEnabled: process.env.CAP_DEBUG === 'true',
    backgroundColor: '#f2f2f7',
  },
  plugins: {
    // Native launch screen = logo on black; the web splash (index.html) takes over and animates.
    // PD-20: no fixed colour — the launch screen uses the app's ground for the phone's
    // light/dark mode (Android res/values[-night]/splash_colors.xml, iOS Splash image set).
    SplashScreen: { launchAutoHide: false, showSpinner: false },
    Keyboard: { resize: KeyboardResize.Native, resizeOnFullScreen: true },
    StatusBar: { overlaysWebView: true, style: 'LIGHT' },
    CapacitorSQLite: { iosIsEncryption: false, androidIsEncryption: false },
  },
};

export default config;
