import type { CapacitorConfig } from '@capacitor/cli';
import { KeyboardResize } from '@capacitor/keyboard';

/**
 * Hosted-URL architecture: the native shell loads the web app from APP_URL in its WebView.
 * Capacitor is used only for native features (SQLite, haptics, status bar, keyboard …).
 * `shell/` is a tiny bundled fallback (offline / load-error page) generated by
 * scripts/build-shell.mjs.
 */
const appUrl = process.env.APP_URL ?? 'https://vk2401.github.io/gym_tracker/';
const appHost = new URL(appUrl).hostname;

const config: CapacitorConfig = {
  appId: 'com.webronian.gymtracker',
  appName: 'Gym Tracker',
  webDir: 'shell',
  server: {
    url: appUrl,
    cleartext: false,
    allowNavigation: [appHost],
    errorPath: 'offline.html',
  },
  ios: {
    contentInset: 'never',
    scrollEnabled: true,
    allowsLinkPreview: false,
    backgroundColor: '#f2f2f7',
    // Needed for the service worker (offline cache) in WKWebView; host listed in
    // Info.plist WKAppBoundDomains.
    limitsNavigationsToAppBoundDomains: true,
  },
  android: {
    allowMixedContent: false,
    captureInput: true,
    webContentsDebuggingEnabled: process.env.CAP_DEBUG === 'true',
    backgroundColor: '#f2f2f7',
  },
  plugins: {
    SplashScreen: { launchAutoHide: false, backgroundColor: '#1e7bf2', showSpinner: false },
    Keyboard: { resize: KeyboardResize.Native, resizeOnFullScreen: true },
    StatusBar: { overlaysWebView: true, style: 'LIGHT' },
    CapacitorSQLite: { iosIsEncryption: false, androidIsEncryption: false },
  },
};

export default config;
