// Pre-loaded muscle categories (BRD §11 assumptions, section 7 examples) with their colours.
export const SEED_CATEGORIES: readonly { id: string; name: string; color: string }[] = [
  { id: 'cat-abs-lower', name: 'Abdominals (Lower)', color: '#f59e0b' },
  { id: 'cat-abs-upper', name: 'Abdominals (Upper)', color: '#fbbf24' },
  { id: 'cat-obliques', name: 'Obliques', color: '#d97706' },
  { id: 'cat-chest', name: 'Chest', color: '#ef4444' },
  { id: 'cat-lats', name: 'Lats', color: '#3b82f6' },
  { id: 'cat-upper-back', name: 'Upper Back', color: '#2563eb' },
  { id: 'cat-lower-back', name: 'Lower Back', color: '#1d4ed8' },
  { id: 'cat-trapezius', name: 'Trapezius', color: '#6366f1' },
  { id: 'cat-front-delts', name: 'Front Delts', color: '#a855f7' },
  { id: 'cat-side-delts', name: 'Side Delts', color: '#c026d3' },
  { id: 'cat-rear-delts', name: 'Rear Delts', color: '#7c3aed' },
  { id: 'cat-biceps', name: 'Biceps', color: '#14b8a6' },
  { id: 'cat-triceps', name: 'Triceps', color: '#0d9488' },
  { id: 'cat-forearms', name: 'Forearms', color: '#0f766e' },
  { id: 'cat-quads', name: 'Quadriceps', color: '#22c55e' },
  { id: 'cat-hamstrings', name: 'Hamstrings', color: '#16a34a' },
  { id: 'cat-glutes', name: 'Glutes', color: '#ec4899' },
  { id: 'cat-calves', name: 'Calves', color: '#84cc16' },
  { id: 'cat-adductors', name: 'Adductors', color: '#65a30d' },
  { id: 'cat-abductors', name: 'Abductors', color: '#4d7c0f' },
  { id: 'cat-cardio', name: 'Cardio', color: '#f97316' },
];

export const SEED_EQUIPMENT: readonly { id: string; name: string }[] = [
  { id: 'eq-none', name: 'None' },
  { id: 'eq-machine', name: 'Machine' },
  { id: 'eq-barbell', name: 'Barbell' },
  { id: 'eq-dumbbell', name: 'Dumbbell' },
  { id: 'eq-cable', name: 'Cable' },
  { id: 'eq-kettlebell', name: 'Kettlebell' },
  { id: 'eq-ez-bar', name: 'EZ Bar' },
  { id: 'eq-smith', name: 'Smith Machine' },
  { id: 'eq-band', name: 'Resistance Band' },
  { id: 'eq-foam-roll', name: 'Foam Roll' },
  { id: 'eq-jump-rope', name: 'Jump Rope' },
  { id: 'eq-bench', name: 'Bench' },
  { id: 'eq-pullup-bar', name: 'Pull-Up Bar' },
];
